resolver: lts-13.0

packages:
- .
- polysemy-plugin

extra-deps:
- dump-core-0.1.3.2
- monadLib-3.9
- ghc-lib-0.20190204
- th-abstraction-0.3.1.0
- inspection-testing-0.4.2
- bifunctors-5.5.4
- aeson-1.4.3.0
